### ISSUE TITLE
[Question] timezone 

### ISSUE THREAD

**Issue by halallah** [xsoh/moment-hijri#12]
Assalam, How can I change timezone for Hijri moment because default moment-hijri current date not same as my country (Malaysia)

**Comment by xsoh** [comment]
Wa Alaekom Alsalam وعليكم السلام,
By default moment will take your system's timezone but if you want to change it to different time then you can do it by [setting the UTC time](http://momentjs.com/docs/#/manipulating/utc-offset/) for example Malaysia is +8 hours so:
```js
m = moment(); 
m.utcOffset("+08:00");
m.format('iYYYY-iM-iD HH:mm:ss'); // 1437-3-24 22:15:41
```

Thanks :+1:

**Comment by Noitidart** [comment]
Is it possible to use this with moment-timezone plugin?
