### ISSUE TITLE
Arabic dates won't appear 

### ISSUE THREAD

**Issue by othmaan** [xsoh/moment-hijri#16]
Even after including
`<script src="locale/ar-sa.js"></script>
`

**Comment by xsoh** [comment]
@othmaan Salam...
Actually, the way to use the Arabic locale has changed but I didn't update the Readme. To use the Arabic locale you need to do as follow:
1- Load the [moment-with-locales](http://momentjs.com/downloads/moment-with-locales.js).
2- Set the global or local locale to `ar-SA` see (here)[http://momentjs.com/docs/#/i18n/changing-locale/].
3- use it normally :+1: 

Here is example:
```html
    <!-- 1- Load the moment-with-locales -->
    <script src="http://momentjs.com/downloads/moment-with-locales.min.js"></script>
    <script src="https://raw.githubusercontent.com/xsoh/moment-hijri/master/moment-hijri.js"></script>
    
    <script>
      moment.locale('ar-SA');// 2- Set the global locale to `ar-SA`
      m = moment();
      $('h1').html('اليوم هو:' + m.format('iDD/iM/iYYYY')) //3- use it normally 
      //اليوم هو:١١/٨/١٤٣٧
    </script>
```

**Comment by othmaan** [comment]
Thanks a lot. It works as charm 😀

**Comment by xsoh** [comment]
Happy to hear that
شكرًا عُثمان Thanks Othmaan  :+1:
