### ISSUE TITLE
iMonth return wrong value

### ISSUE THREAD

**Issue by abublihi** [xsoh/moment-hijri#34]
Hi, (السلام عليكم)
iMonth function return wrong value, for example the date is **1439/8/19** in this case it should return **8** but it returns **7** .

Thank You

**Comment by xsoh** [comment]
Hello وعليكم السلام,
Is this issue still returning wrong value?

**Comment by abublihi** [comment]
hi اهلاً,
yes it still return wrong value as shown in the example, but i think it is not wrong it may be how the program was structured.

if you can solve it, will be better 😃 .

**Comment by xsoh** [comment]
Correct, according to[ moment's documentation ](https://momentjs.com/docs/#/get-set/month/)the `Month()` method is zero indexed. so it it starts from **0 to 11**. So this case is correct as of [test case in line 364](https://github.com/xsoh/moment-hijri/blob/master/test.js#L364).

Finally, this is not an issue as of the documentation 😀 

Thanks
