### ISSUE TITLE
Illogical return from isSame()

### ISSUE THREAD

**Issue by mazenadel19** [xsoh/moment-hijri#73]
**Description**: comparing 1443/11/01 to 1443/10/01 returns true also it should return false

**Steps to replicate the bug**: ```moment('1443/11/01', 'iYYYY/iMM/iDD').isSame(moment('1443/10/01', 'iYYYY/iMM/iDD'),'month')```

**Comment by diana96alazzam** [comment]
Use `iMonth` instead of month.

`moment('1443/11/01', 'iYYYY/iMM/iDD').isSame(moment('1443/10/01', 'iYYYY/iMM/iDD'),'iMonth')`

**Comment by mazenadel19** [comment]
Hmm, I think you're correct, I'm not sure why I used `month` instead of `iMonth` then 🤔
To my surprise, I tested `isSame` with `month` and `iMonth` and I found that it is returning `false` in both cases now. 
I will go ahead and close this issue. Thanks for your help!
