### ISSUE TITLE
I believe npmjs need to get latest update from here 

### ISSUE THREAD

**Issue by som3ah01** [xsoh/moment-hijri#88]
Kindly Brother i see here all up to date 
I believe npmjs need to be updated and version be upgraded
https://www.npmjs.com/package/moment-hijri/v/2.1.2
neep to push the updates there 
for example  some versions  like "moment": "^2.24.0" need to get latest update from here 

Many thanks in advance

**Comment by xsoh** [comment]
Done. Thanks 👍
