### ISSUE TITLE
daysInMonth always return gregorian month lengh

### ISSUE THREAD

**Issue by OmarHassan25** [xsoh/moment-hijri#9]
Please how i can get hijri month lenght, i am using daysInMonth but it always return gregorian month lengh.
here is my code 

   var m = moment('1410/8/28', 'iYYYY/iM/iD');
 
          var v1=  m.iYear(); // 1410
          var v2 = m.iMonth(); // 7
          var v3 = m.iDate(); // 28
          var v4 = m.iDayOfYear(); // 236
          var v5 = m.iWeek(); // 35
          var v6 = m.iWeekYear(); // 1410
          var v7= m.daysInMonth();

**Comment by xsoh** [comment]
Hmm.. it seems to be not implemented yet.
As quick solution you can use `var v7= m.endOf('iMonth').format('iDD'); `

**Comment by OmarHassan25** [comment]
Thanks a lot, it is working

**Comment by xsoh** [comment]
@OmarHassan25 Thank you for reporting about the bug and please let me keep the issue opened until its fixed because what I gave you was just workaround but not a fix of the problem.
Thanks again :+1:
